version: "3.8"

services:
    nodejs:
        build:
            context: "./web"
            dockerfile: Dockerfile.nodejs
        ports:
            - "3000:3000"
        depends_on:
            - mongodb

    mongodb:
        image: mongo:latest
        build:
            context: "./db"
            dockerfile: Dockerfile.db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: myapp
        ports:
            - "27017:27017"
        volumes:
            - db:/data/db

volumes:
    db: