# Use an official MongoDB image as the base image
FROM mongo:latest

# Expose the default MongoDB port
EXPOSE 27017

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=admin \
  MONGO_INITDB_ROOT_PASSWORD=password \
  MONGO_INITDB_DATABASE=myapp

# Copy initialization scripts
COPY init-scripts /docker-entrypoint-initdb.d